"""add email to user_sessions

Revision ID: 675bda9e8c88
Revises: 001
Create Date: 2026-04-12 22:14:59.604216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '675bda9e8c88'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_target_id'), 'activity_logs', ['target_id'], unique=False)
    op.alter_column('bookings', 'booking_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('bookings', 'booking_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('bookings', 'line_notified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bookings', 'hour_returned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cancel_policies', 'hours_before',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cancel_policies', 'return_hour',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('caretakers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('customer_code_counters', 'last_sequence',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=0),
               nullable=False)
    op.alter_column('customer_hour_balances', 'remaining',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_index(op.f('ix_customer_hour_logs_created_at'), 'customer_hour_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_hour_logs_customer_id'), 'customer_hour_logs', ['customer_id'], unique=False)
    op.alter_column('customers', 'is_duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('feature_toggles', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('login_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.drop_constraint(op.f('login_attempts_user_id_fkey'), 'login_attempts', type_='foreignkey')
    op.drop_column('login_attempts', 'user_id')
    op.drop_column('login_attempts', 'ip_address')
    op.alter_column('orders', 'hours',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=0),
               nullable=False)
    op.alter_column('orders', 'bonus_hours',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=0),
               nullable=False)
    op.alter_column('orders', 'paid_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('orders', 'is_renewal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('packages', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.alter_column('packages', 'sale_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('packages', 'branch_scope',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'packages', 'branches', ['branch_id'], ['id'])
    op.alter_column('partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('partners', 'updated_at')
    op.drop_column('partners', 'created_at')
    op.alter_column('password_reset_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'password_reset_tokens', ['token_hash'])
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('permission_matrix', 'is_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_permission_matrix_role'), 'permission_matrix', ['role'], unique=False)
    op.alter_column('pin_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('pin_attempts_user_id_fkey'), 'pin_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'pin_attempts', 'users', ['user_id'], ['id'])
    op.alter_column('pin_otps', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pin_otps', 'request_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('pin_otps_user_id_fkey'), 'pin_otps', type_='foreignkey')
    op.create_foreign_key(None, 'pin_otps', 'users', ['user_id'], ['id'])
    op.alter_column('source_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_source_type_branch_code'), 'source_types', type_='unique')
    op.drop_constraint(op.f('source_types_branch_id_fkey'), 'source_types', type_='foreignkey')
    op.create_foreign_key(None, 'source_types', 'branches', ['branch_id'], ['id'])
    op.drop_column('source_types', 'is_active')
    op.drop_column('source_types', 'created_at')
    op.alter_column('trainers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_preferences', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('user_preferences', 'dark_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('user_sessions', sa.Column('email', sa.String(length=255), nullable=True))
    op.execute("DELETE FROM user_sessions WHERE email IS NULL")
    op.alter_column('user_sessions', 'email', nullable=False)
    op.alter_column('user_sessions', 'token_jti',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('user_sessions_token_jti_key'), 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_token_jti'), 'user_sessions', ['token_jti'], unique=True)
    op.drop_constraint(op.f('user_sessions_user_id_fkey'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'pin_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'pin_attempts')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pin_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('users', 'pin_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('user_sessions_user_id_fkey'), 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_sessions_token_jti'), table_name='user_sessions')
    op.create_unique_constraint(op.f('user_sessions_token_jti_key'), 'user_sessions', ['token_jti'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_sessions', 'token_jti',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user_sessions', 'email')
    op.alter_column('user_preferences', 'dark_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_preferences', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('trainers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('source_types', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('source_types', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'source_types', type_='foreignkey')
    op.create_foreign_key(op.f('source_types_branch_id_fkey'), 'source_types', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_source_type_branch_code'), 'source_types', ['branch_id', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('source_types', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'pin_otps', type_='foreignkey')
    op.create_foreign_key(op.f('pin_otps_user_id_fkey'), 'pin_otps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pin_otps', 'request_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pin_otps', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'pin_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('pin_attempts_user_id_fkey'), 'pin_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pin_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_permission_matrix_role'), table_name='permission_matrix')
    op.alter_column('permission_matrix', 'is_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.alter_column('password_reset_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('partners', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('partners', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.alter_column('packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('packages', 'branch_scope',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('packages', 'sale_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('packages', 'branch_id')
    op.alter_column('orders', 'is_renewal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('orders', 'paid_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('orders', 'bonus_hours',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'hours',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=sa.INTEGER(),
               nullable=True)
    op.add_column('login_attempts', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('login_attempts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('login_attempts_user_id_fkey'), 'login_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.alter_column('login_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('feature_toggles', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('customers', 'is_duplicate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_customer_hour_logs_customer_id'), table_name='customer_hour_logs')
    op.drop_index(op.f('ix_customer_hour_logs_created_at'), table_name='customer_hour_logs')
    op.alter_column('customer_hour_balances', 'remaining',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('customer_code_counters', 'last_sequence',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('caretakers', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('cancel_policies', 'return_hour',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cancel_policies', 'hours_before',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('branches', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bookings', 'hour_returned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bookings', 'line_notified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bookings', 'booking_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('bookings', 'booking_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_activity_logs_target_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    # ### end Alembic commands ###
