"""multi-branch users: drop User.branch_id, add user_branches join table

Revision ID: b7f4a1c9d2e3
Revises: c01ad1b96c63
Create Date: 2026-04-18 10:00:00.000000

Moves User→Branch from single-valued column to many-to-many via a join table.
Backfill copies each existing users.branch_id into user_branches before
dropping the old FK + column. Unrestricted roles (OWNER/DEVELOPER) keep an
empty row-set on this table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f4a1c9d2e3'
down_revision: Union[str, None] = 'c01ad1b96c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. New association table.
    op.create_table(
        'user_branches',
        sa.Column('user_id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'branch_id'),
    )

    # 2. Backfill: copy every (user.id, user.branch_id) where branch_id IS NOT NULL.
    op.execute(
        """
        INSERT INTO user_branches (user_id, branch_id)
        SELECT id, branch_id FROM users WHERE branch_id IS NOT NULL
        ON CONFLICT DO NOTHING
        """
    )

    # 3. Drop the old FK + column on users.
    #    Constraint name is autogenerated; use the runtime lookup pattern.
    with op.batch_alter_table('users') as batch_op:
        # drop any FK pointing from users.branch_id → branches.id
        # (name differs per env; use a reflective drop)
        batch_op.drop_constraint('users_branch_id_fkey', type_='foreignkey')
        batch_op.drop_column('branch_id')


def downgrade() -> None:
    # 1. Re-add users.branch_id (nullable).
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.UUID(as_uuid=True), nullable=True))
        batch_op.create_foreign_key(
            'users_branch_id_fkey', 'branches', ['branch_id'], ['id'],
        )

    # 2. Best-effort back-copy: take the first branch_id per user from user_branches.
    op.execute(
        """
        UPDATE users
        SET branch_id = sub.branch_id
        FROM (
            SELECT DISTINCT ON (user_id) user_id, branch_id
            FROM user_branches
            ORDER BY user_id, branch_id
        ) sub
        WHERE users.id = sub.user_id
        """
    )

    # 3. Drop association table.
    op.drop_table('user_branches')
